### ISSUE TITLE
openwrt-builddeps package

### ISSUE THREAD

**Issue by alexlist** [ffgraz/infrastructure#2]
Initial version:

Hard code builddeps for OpenWRT buildroot based on 
http://wiki.openwrt.org/doc/howto/buildroot.exigence

and make a virtual package that pulls in these dependencies.

Improvement: Detect builddeps based on specified OpenWRT git branch automatically and try to install them.

**Comment by nbraud** [comment]
Done by @alexlist in https://github.com/ffgraz/openwrt-meta
